name: auto-invite
description: Send invitation based on issue label
author: Danil Zasypkin
branding:
  icon: anchor
  color: green
inputs:
  organization:
    description: Name of the organization to which you would like to invite contributors.
    required: true
  label:
    description: Name of the label
    required: true
  repo-token:
    description: 'GitHub token for repo'
    required: true
  role:
    description: 'GitHub user role'
    required: true
    default: member
  comment:
    description: A comment which will be posted on the issue.
    required: false
    default: Invitation sent for the GitHub Organisation. Welcome to the community
  existingMemberMessage:
    description: Message for existing organisation members
    required: false
    default: You are already a member of our Organisation.
runs:
  using: node16
  main: dist/index.js
